# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = [workspace 2 silent] brave-browser
# Start 1Password (optional, GUI app, not the CLI)
exec-once = [workspace 3 silent] 1password
# Start Discord (optional)
exec-once = [workspace 4 silent] discord
