# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Window rules
# Send Brave windows to workspace 2 (robust case-insensitive match)
windowrule {
  name = windowrule-1
  workspace = 2
  match:class = ^(?i)brave(-browser)?$
}

# Send 1Password windows to workspace 3 (robust case-insensitive match)
windowrule {
  name = windowrule-2
  workspace = 3
  match:class = ^(?i)1password(\.app)?$
}

# Send Brave ChatGPT windows to workspace 3 (robust case-insensitive match)
windowrule {
  name = windowrule-3
  workspace = 3
  match:class = ^(?i)brave-chatgpt.com__-Default$
}

# Send Discord windows to workspace 4 (robust case-insensitive match)
windowrule {
  name = windowrule-4
  workspace = 4
  match:class = ^(?i)discord$
}


# Send Steam windows to workspace 5 (robust case-insensitive match)
# Make Steam windows always maximized
windowrule {
  name = windowrule-5
  workspace = 5
  maximize = on
  match:class = ^(?i)steam$
}

